### ISSUE TITLE
v0.0.4 tag moved

### ISSUE THREAD

**Issue by acuteaura** [gin-contrib/requestid#17]
the head for v0.0.4 seems to have moved at least once in the lifespan of the project; the caching server for fly.io has a different `go.sum` checksum

```
verifying github.com/gin-contrib/requestid@v0.0.4: checksum mismatch
   downloaded: h1:XKTeDRVmaVk6mdZrLKujeK+Q3GXWPgrbYu+2akE5XMQ=
   go.sum:     h1:jZhoc2L8MMnxZBgV6c6BD9Ly4/k8TGa1PwnH2GuvVoA=
```

**Comment by bastengao** [comment]
Got the same issue.

**Comment by acuteaura** [comment]
Workaround is to pin to a commit without tag.

```
go get github.com/gin-contrib/requestid@b1a110440cfd0c83c22c7185e0da8d72985b7bae
```

**Comment by appleboy** [comment]
https://github.com/gin-contrib/requestid/releases/tag/v0.0.5
