### ISSUE TITLE
RequestId on Request Header

### ISSUE THREAD

**Issue by danieldias51** [gin-contrib/requestid#27]
Hi,

Was trying this lib, and notice the Request ID is only set on the response headers and not on the request.
I want to get the request id from the gin context for logging and other purposes.

How about setting the request header in both request and response objects?

**Comment by pscheid92** [comment]
I agree with you @danieldias51.

### Use Case
We want to add the generated request-id to our logs. On errors, we display the request-id on our error page. Support can search for the request-id in our centralised logging system to get an overview.


### Workaround
One can extract the generated request-id from the writer.
```go
r.GET("/something", func(c *gin.Context) {
    rid := c.Writer.Header().Get("X-Request-Id")
})
```


### Proposal
We could easily extend the middleware to attach the generated request-id to the context in multiple ways. For reference, see the current implementation:

https://github.com/gin-contrib/requestid/blob/a2cd79bd41afcbe40de5faf87158340ac588f055/requestid.go#L34-L47

<br>

#### Request Header

There is already a check if a request-id is set in the request headers. If none is present, we generate a new one. At this very moment, we could attach that newly generated one as a request header.

```go
// Get id from request
rid := c.GetHeader(string(cfg.headerKey))
if rid == "" {
    rid = cfg.generator()
    c.Request.Header.Set(string(cfg.headerKey))
}
```

```go
r.GET("/something", func(c *gin.Context) {
    rid := c.GetHeader("X-Request-Id")
})
```

<br>

#### Context Key-Value Pair

While writing the request id to the response headers, we could add it also as a new key-value pair to the request context.

```go
// Set the id to ensure that the requestid is in the response
c.Header(headerXRequestID, rid)
c.Set(headerXRequestID, rid
c.Next()
```

```go
r.GET("/something", func(c *gin.Context) {
    rid := c.GetString("X-Request-Id")
})
```

**Comment by pscheid92** [comment]
Forget what I answered before! 

I just discovered that we already added that feature with #5!
But it got **accidentally deleted** again in #8!

@appleboy Could we add it again?

**Comment by pscheid92** [comment]
**Workaround**
We already[ provide a function to extract](https://pkg.go.dev/github.com/gin-contrib/requestid?utm_source=godoc#Get) the request-id from the response headers.

```go
r.GET("/something", func(c *gin.Context) {
    rid := requestid.Get(c)
})
```

**Comment by appleboy** [comment]
https://github.com/gin-contrib/requestid/releases/tag/v0.0.6
