### ISSUE TITLE
Putting the Request ID as Request Header

### ISSUE THREAD

**Issue by AryeShemesh** [gin-contrib/requestid#6]
Hi,

Currently the request ID is stored in and retrieved from the gin context.

I wanted to add the request ID to the gin logging output. The problem is that gin logger currently accepts a [LogFormatterParams](https://github.com/gin-gonic/gin/blob/336ce0d47532e89657b711af52bf5a8e01128755/logger.go#L56) struct with the Request object and not the Context object, so even if I provide a [custom LogFormatter](https://github.com/gin-gonic/gin/blob/336ce0d47532e89657b711af52bf5a8e01128755/logger.go#L53), I cannot log the request ID that way.

Can you add an option to add the request ID as a header to the request, or to the context.Keys map?

**Comment by appleboy** [comment]
fixed by #5

**Comment by appleboy** [comment]
bump to v0.0.2 version https://github.com/gin-contrib/requestid/releases/tag/v0.0.2
